### ISSUE TITLE
Cordova Badge not working in Android 6

### ISSUE THREAD

**Issue by Siva-93** [katzer/cordova-plugin-badge#79] opened 2016-10-31 06:36 UTC
Hi, 
I'm developing an android application which has local-notification features. My functionality is very simple. I need to show the badge whenever the notification arises in the app. However this is nicely working in android 4.4 and 5. But the weird thing is the same code is not working in Android 6.

 What  might be the cause? Is android OS suspends all the running process in background?. Kindly help me to get out from this problem.

 Plugin details:
    cordova = 6.4
    katzer/local-notification = 0.8.4
    katzer/badge = 0.7.2

**Comment by marcoliceti** [comment] 2016-11-09 15:49
Same here.

**Comment by alaa-alshamy** [comment] 2016-11-23 06:23
yep same here , although it's work on ShortcutBadger's test project 

i installed their test app it's name "ShortcutBadger - Check tool" in play store

and the badge work as expected but here in this plugin doesn't work i don't know why

**Comment by hungkun** [comment] 2016-12-19 09:44
same here

**Comment by katzer** [comment] 2016-12-30 17:47
See #81 Would be great if someone can tell me if v.0.7.4 does work with Android 6.

**Comment by alaa-alshamy** [comment] 2016-12-31 05:16
ok i will give it a try

**Comment by alaa-alshamy** [comment] 2016-12-31 06:57
unfortunately still not working , i tried it on sony m5 and android version is 6.0

Note: it's working as expected on shourtcut badger's test project but here in this plugin not working

**Comment by katzer** [comment] 2016-12-31 11:03
Now I've tested with NOVA Launcher installed on the device emulator and its working on Android 6 & 7.
Looks to me that its not an issue with Android 6 and the plugin in general.

<p align="center">
    <img width="49%" src="https://cloud.githubusercontent.com/assets/2039384/21577139/77e4730a-cf50-11e6-8e5e-6b6b165a9aa1.png"></img>
    &nbsp;
    <img width="49%" src="https://cloud.githubusercontent.com/assets/2039384/21577138/77e3a8d0-cf50-11e6-9bbf-6197eda4b561.png"></img>
</p>

<p align="center">
    <img width="49%" src="https://cloud.githubusercontent.com/assets/2039384/21577137/77e364ce-cf50-11e6-982e-c7cba15d02fd.png"></img>
    &nbsp;
    <img width="49%" src="https://cloud.githubusercontent.com/assets/2039384/21577136/77e29d64-cf50-11e6-893e-2cf6e978c309.png"></img>
</p>

**Comment by Siva-93** [comment] 2017-01-02 06:34
Thanks for the reply. I'll try and let you know @katzer

**Comment by menzow** [comment] 2017-01-09 07:40
I can confirm that this isn't working at version 0.7.4 for android 6.

**Comment by menzow** [comment] 2017-01-09 07:48
@katzer that's odd, for me this application also does not work.
![screenshot_20170109-144709](https://cloud.githubusercontent.com/assets/5744434/21759916/b1144dc2-d67a-11e6-879e-4584c647f534.png)
![screenshot_20170109-144736](https://cloud.githubusercontent.com/assets/5744434/21759917/b116505e-d67a-11e6-87fd-51561cf9dbe4.png)

**Comment by marlosirapuan** [comment] 2017-01-11 21:19
same here.. : (

**Comment by katzer** [comment] 2017-01-15 09:16
@menzow As you have installed the NOVA launcher. Did you also install TeslaUnread-for-Nova-Launcher with granted permissions,...? That requires the PRO version of NOVA.

Anyway if ShortcutBadger does not support the platform or mix of device manufacturer and launcher, then the plugin wont work also. However that needs to be fixed on ShortcutBadger side.

**Comment by alaa-alshamy** [comment] 2017-01-16 10:34
@katzer what about another cases , when ShortcutBadger work and this plugin does not work ? 

what should we do ?

**Comment by menzow** [comment] 2017-01-16 12:02
@katzer Hey, thanks for your reply.

Yea I installed Nova launcher per your test case. My default launcher didn't allow it.
Seems there's multiple issues with the current project.

Do you know of any alternatives?

**Comment by katzer** [comment] 2017-01-18 15:04
@alaa-alshamy 

> what about another cases , when ShortcutBadger work and this plugin does not work ?

Then I need an error message or code so I can reproduce the issue. I haven't yet had this constellation.

**Comment by katzer** [comment] 2017-01-18 15:08
@menzow 

> Do you know of any alternatives?

ShortcutBadger is by far the best lib for it and I really appreciate his work. Keep in mind that badges aren't supported by core Android. Every launcher and device manufacturer has his own way, rules. Its complicated to test everything...

**Comment by alaa-alshamy** [comment] 2017-02-03 08:37
@katzer there's no error msg or code appear on logcat when calling set badge function , and it's work as expected and return the number that it should be set in badge but nothing appear on app icon

any suggestion how to figure out the problem ?

note: it's work as expected with shortcutBadger's test app

**Comment by leolin310148** [comment] 2017-02-04 07:17
Hi, it's time to update ShortcutBadger to 1.1.13 which updated for:
* support new sony badger
* handle legacy Samsung devices
* Fix Xiaomi miui6+

**Comment by alaa-alshamy** [comment] 2017-02-04 13:36
@leolin310148 it's not ShortcutBadger problem because it's work on ShortcutBadger's test app , there's problem in this plugin i don't know what is it

but i upgraded the shortcutBadger to 1.1.13 in this plugin and got same problem.

btw there's problem with new version of ShortcutBadger , my samsung phone not showing the badge after upgrade the ShortcutBadger's test app to latest and it was working before upgrade, and i sent info that's not working on the app.

**Comment by katzer** [comment] 2017-02-04 15:24
@leolin310148 

First of all thanks for your lib!

Some users reported that on the same device the plugin doesn't work but your test app does. Does your test app is doing something special thats not included in my code?

**Comment by alaa-alshamy** [comment] 2017-02-05 12:44
@katzer 
leoline's test app is open source so if u can figure what's you missed comparing with his test app for us that's will be great bro :)

and thanks anyway :)

link of leoline test app : 
https://github.com/leolin310148/IsBadgeWorking.Android

**Comment by katzer** [comment] 2017-02-06 08:42
@alaa-alshamy As you can imagine, that was the first step I did when the topic came up ;)

- plugin:
https://github.com/katzer/cordova-plugin-badge/blob/master/src/android/BadgeImpl.java#L86
- test app:
https://github.com/leolin310148/IsBadgeWorking.Android/blob/master/app/src/main/kotlin/me/leolin/isbadgeworking/MainActivity.kt#L62

**Comment by alaa-alshamy** [comment] 2017-02-09 13:59
@katzer  oh sorry man i thought u didn't :) , but really this bug made me crazy I'm really obsessed to solve it xD

**Comment by nicksterFL** [comment] 2017-02-25 12:52
It looks like the config.xml is missing the addition of the plugin. I added: <plugin name="cordova-plugin-badge" /> to the config.xml and the badge was working on android 6.

**Comment by nicksterFL** [comment] 2017-02-25 12:52
`<plugin name="cordova-plugin-badge" />`

**Comment by djtruco** [comment] 2017-03-15 04:33
Hi @nicksterFL, could you tell us the location of config.xml file? Also an example of that file to be sure.

Thanks in advance!

**Comment by menzow** [comment] 2017-03-20 21:04
Hey @nicksterFL, in addition to your android version could you please also provide device info (Brand & model). Like @katzer mentioned, badges are not supported by core android and thus implementation varies between vendors.

@djtruco : `config.xml` can be found in your cordova / ionic / phonegap projects **root** folder. More info: https://cordova.apache.org/docs/en/latest/config_ref/

**Comment by djtruco** [comment] 2017-03-21 02:43
Thanks @menzow for your reply. This solve the first problem I described in [this issue](https://github.com/katzer/cordova-plugin-badge/issues/89) (in [Sample App](https://github.com/katzer/cordova-plugin-badge/tree/example) cordova-plugin-badge directory is a symbolic link to a folder in Sebastian's file system) but I still have problems with the other broken symbolic links and I can't get this [Sample App](https://github.com/katzer/cordova-plugin-badge/tree/example) working, but the one for ShortcutBadger, [IsBadgeWorking](https://github.com/leolin310148/IsBadgeWorking.Android/), works fine for me (Sony Xperia Z5 E6833, Android 7.0).

**Comment by menzow** [comment] 2017-03-21 04:32
Hey @djtruco, this is probably because both sample apps use different versions of ShortcutBadger.

The latest version (1.1.13) is used by IsBadgeWorking (https://github.com/leolin310148/IsBadgeWorking.Android/commit/f205892e8e1369b10d57065eb420358d9acae9bb).
@katzer's sample app runs version 1.1.11 (https://github.com/katzer/cordova-plugin-badge/blob/06b4e1e224a4a7bb8c1b5c5c56349e14882b596f/CHANGELOG.md#L3)

Support for your specific device might have been added in 1.1.12 or later. You can find the ShortcutBadger change log here: https://github.com/leolin310148/ShortcutBadger#change-log

**Comment by djtruco** [comment] 2017-03-21 14:11
Hi @menzow, I already tested [IsBadgeWorking](https://github.com/leolin310148/IsBadgeWorking.Android/) with [ShortcutBadger](https://github.com/leolin310148/ShortcutBadger) versions **[1.1.11](https://cloud.githubusercontent.com/assets/9561083/24151109/c5c26024-0e15-11e7-9d2b-6a3f1a124292.png)**, **[1.1.13](https://cloud.githubusercontent.com/assets/9561083/24151110/c5dc47b4-0e15-11e7-84dd-80d0480923c1.png)** and the newest **[1.1.14](https://cloud.githubusercontent.com/assets/9561083/24151108/c5c1fc42-0e15-11e7-82fc-61f90ee7f01b.png)**, all of them works fine in my physical phone (Sony Xperia Z5 E6833, Android 7.0).

Also I tried to make the @katzer's [Sample App](https://github.com/katzer/cordova-plugin-badge/tree/example) use [ShortcutBadger](https://github.com/leolin310148/ShortcutBadger)version **1.1.13** or **1.1.14** but any way, I can't get it work.

**Comment by menzow** [comment] 2017-03-21 17:09
Hey @djtruco, Thanks for the info.

I just had some time to actually run the Sample App again. I ran it on my samsung SM-G570Y, android 6.0.1, com.sec.android.app.launcher (no badges apearing..).

Upgrading the ShortcutBadger library to 1.1.14 did resolve the issues for me. I can't say what the exact cause or fix was, but it is related to the <uses-permission ...> tags defined in AndroidConfig.xml.

I did find the following exception: [ShortcutBadger.java:93](https://github.com/leolin310148/ShortcutBadger/blob/759adbb78e329b09552c417288f155058443223a/ShortcutBadger/src/main/java/me/leolin/shortcutbadger/ShortcutBadger.java#L93)
```
Permission Denial: writing com.sec.android.provider.badge.BadgeProvider uri content://com.sec.badge/apps?notify=true from pid=7568, uid=10170 requires com.sec.android.provider.badge.permission.WRITE, or grantUriPermission()
```

This exception has been reported a couple of times in the ShortcutBadger repo, however there's no clear cause or solution. In my case the required <uses-permissions> tags were defined but the permissions were not granted.

I'll see if I can make a clean PR later this week.

![group 2](https://cloud.githubusercontent.com/assets/5744434/24160234/89d817c4-0e61-11e7-8891-61bf14016b00.png)

**Comment by djtruco** [comment] 2017-03-23 03:59
Hello @menzow can you share the APK you builded to test it on my phone?

I decompiled the produced APK and I'm sure that all the required `<uses-permissions>` tags are present.

How do you traced that exception? excuse me if is a silly question.

Thanks!

**Comment by menzow** [comment] 2017-03-23 16:12
@djtruco I open the `platforms/android` directory in Android Studio and run the APK in debug mode from there. This allows me to set breakpoints and view all debug output.

As for the APK, here you go:
[android-debug.apk.zip](https://github.com/katzer/cordova-plugin-badge/files/865376/android-debug.apk.zip)

**Comment by djtruco** [comment] 2017-03-23 23:00
Thanks @menzow, I'll try to run the app in debug mode as you suggested and will post my observations.

The bad thing: I installed your APK in my phone and the badge didn't worked :S

![image](https://cloud.githubusercontent.com/assets/9561083/24273838/a1f5882c-0ff2-11e7-9e35-acd658a8699b.png)

**Comment by cmartin81** [comment] 2017-04-20 19:14
I got it to work!
I had to install https://github.com/alaa-alshamy/cordova-plugin-badge/commit/ba356e4d1e8beb4aa7e6777118777b99f042164c (only upgrade to 1.1.13) and after this it worked :)

**Comment by djtruco** [comment] 2017-04-20 19:37
Nice to know it! Did you know [ShortcutBadger](https://github.com/leolin310148/ShortcutBadger) is now at 1.1.16 version? Try it to be in the last one and please report your experience. Thanks.

**Comment by LKhromov** [comment] 2017-05-01 05:57
My test device is Sony Xperia Z2, Android 6. The only thing that helped me to get badges was upgrade to version 1.1.16 of ShortcutBadger. It didn't work with 1.1.13.

**Comment by hungkun** [comment] 2017-05-06 08:55
LKhromov, 
You can clone source code of this plugin, extract it on your computer. And then change value of  dependencies : "compile 'me.leolin:ShortcutBadger:1.1.11@aar'" in file badge.gradle on src/android/badge.gradle to compile "me.leolin:ShortcutBadger:1.1.16@aar"

After that reinstall plugin of you Cordova project and rebuild android platform project.

Hope this help.

**Comment by LKhromov** [comment] 2017-05-06 13:29
hungkun,
I've done exactly what you suggested. Thats why I said in post that version upgrade had helped me. Anyway thanks for detailed instruction,would be usefull for someone.

**Comment by katzer** [comment] 2017-06-06 14:25
Folks, with next version you will be able to specify the version of ShortcutBadge via Cordova preference. See https://github.com/katzer/cordova-plugin-badge/commit/b794968ec0cda7f45de949a61811fa113673a7a6 for early adopters.

**Closed** 2017-07-10 09:55 UTC
Labels: question
